//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutanaklar
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirimFiyatTbl
    {
        public int PozId { get; set; }
        public string PozNo { get; set; }
        public string Cinsi { get; set; }
        public string Birim { get; set; }
        public Nullable<double> MalzemeBirimFiyat { get; set; }
        public Nullable<double> IscilikBirimFiyat { get; set; }
    }
}
